package main.java.me.avankziar.tt.spigot.cmdtree;

public enum CommandExecuteType
{
	TT,
	TT_CHECKEVENTACTION,
	TT_CHECKPLACEDBLOCKS,
	TT_GIVEITEM,
	TT_RELOAD,
	TT_TECHINFO,
	
	TT_GROUP,
	TT_GROUP_APPLICATION,
	TT_GROUP_APPLICATION_ACCEPT,
	TT_GROUP_APPLICATION_DENY,
	TT_GROUP_APPLICATION_LIST,
	TT_GROUP_APPLICATION_SEND,
	TT_GROUP_CREATE,
	TT_GROUP_DEMOTE,
	TT_GROUP_DONATE,
	TT_GROUP_INCREASELEVEL,
	TT_GROUP_INFO,
	TT_GROUP_INVITE,
	TT_GROUP_INVITE_ACCEPT,
	TT_GROUP_INVITE_DENY,
	TT_GROUP_INVITE_SEND,
	TT_GROUP_KICK,
	TT_GROUP_LEAVE,
	TT_GROUP_LIST,
	TT_GROUP_PLAYERINFO,
	TT_GROUP_PROMOTE,
	TT_GROUP_SETDEFAULT_UPKEEP,
	TT_GROUP_SETDESCRIPTION,
	TT_GROUP_SETGRANDMASTER,
	TT_GROUP_SETINDIVIDUAL_UPKEEP,
	TT_GROUP_SETPRIVILEGES,
	
	TT_TTEXP_ADD,
	TT_TTEXP_SET,
	
	TECHGUI,
}
