package main.java.me.avankziar.tt.spigot.cmdtree;

public enum CommandExecuteType
{
	TT,
	TT_CHECKEVENTACTION,
	TT_CHECKPLACEDBLOCKS,
	TT_GIVEITEM,
	TT_RELOAD,
	TT_TECHINFO,
	
	TT_GROUP,
	TT_GROUP_ACCEPTAPPLICATION,
	TT_GROUP_ACCEPTINVITE,
	TT_GROUP_CREATE,
	TT_GROUP_DEMOTE,
	TT_GROUP_DONATE,
	TT_GROUP_INCREASELEVEL,
	TT_GROUP_INFO,
	TT_GROUP_KICK,
	TT_GROUP_LIST,
	TT_GROUP_LISTAPPLICATION,
	TT_GROUP_PLAYERINFO,
	TT_GROUP_PROMOTE,
	TT_GROUP_SENDAPPLICATION,
	TT_GROUP_SENDINVITE,
	TT_GROUP_SETDEFAULT_UPKEEP,
	TT_GROUP_SETDESCRIPTION,
	TT_GROUP_SETGRANDMASTER,
	TT_GROUP_SETINDIVIDUAL_UPKEEP,
	TT_GROUP_SETPRIVILEGES,
	
	TECHGUI,
}
